version: "3"

services:
  db:
    container_name: postgresdb-BasantBookFestival
    image: postgres:latest
    restart: always
    env_file:
      - project.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    container_name: BasantBookFestival
    build: .
    command: gunicorn BasantBookFestival.wsgi:application --bind 0.0.0.0:8000 --workers=4 --timeout 600
    env_file:
      - project.env
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    volumes:
      - staticfiles:/home/app/web/staticfiles
      - media:/home/app/web/media

  nginx:
    container_name: nginx
    image: nginx:mainline-alpine
    restart: always
    ports:
      - 1337:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - staticfiles:/home/app/web/staticfiles
    depends_on:
      - web

  celery:
    build: .
    command: celery -A BasantBookFestival worker --loglevel=INFO
    volumes:
      - redisdata:/home/app/web/redis
    depends_on:
      - web
      - redis

  redis:
    image: "redis:alpine"

volumes:
  postgres-data:
  staticfiles:
  media:
  redisdata:
