# Generated by Django 3.0.7 on 2021-02-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookFest', '0002_book_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
