# Generated by Django 3.0.7 on 2021-01-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookFest', '0002_book_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='publisher_logos'),
        ),
    ]
