# Generated by Django 3.0.7 on 2021-02-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookFest', '0003_auto_20210203_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='department',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
