# Generated by Django 3.0.7 on 2021-01-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookFest', '0003_publisher_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='supplier',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
