# Generated by Django 3.0.7 on 2021-01-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookFest', '0004_auto_20210127_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='supplier',
        ),
    ]
