# Generated by Django 3.0.7 on 2021-01-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookFest', '0005_remove_book_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='supplier',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
