# Generated by Django 3.0.7 on 2021-01-27 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookFest', '0010_auto_20210127_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='suply',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='expected_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='price_foreign_currency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='price_indian_currency',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
